# Inserting users data
INSERT INTO loyalty.user (login, name, password, surname, user_role, annual_salary) VALUES ('bohdansh', 'Bohdan', '123', 'Shar', 3, 10000);
INSERT INTO loyalty.user (login, name, password, surname, user_role, annual_salary) VALUES ('invaniv', 'Ivan', '222', 'Ivanov', 2, 10000);
INSERT INTO loyalty.user (login, name, password, surname, user_role, annual_salary) VALUES ('petr222', 'Petro', '123444', 'Petrovich', 2, 10000);
INSERT INTO loyalty.user (login, name, password, surname, user_role, annual_salary) VALUES ('12', 'Hulio', '12', 'Ignesias', 1, 10000);
INSERT INTO loyalty.user (login, name, password, surname, user_role, annual_salary) VALUES ('22', 'Enricio', '22', 'Enry', 4, 10000);
INSERT INTO loyalty.user (login, name, password, surname, user_role, annual_salary) VALUES ('hen', 'Henry', 'hen', 'Duglas', 0, 10000);
INSERT INTO loyalty.user (login, name, password, surname, user_role, annual_salary) VALUES ('mac', 'Maccoley', 'mac', 'Calcin', 3, 10000);
INSERT INTO loyalty.user (login, name, password, surname, user_role, annual_salary) VALUES ('che', 'Cheese', 'che', 'Bacon', 1, 10000);
INSERT INTO loyalty.user (login, name, password, surname, user_role, annual_salary) VALUES ('ff', 'Fabric', 'ff', 'Fabricio', 1, 10000);
INSERT INTO loyalty.user (login, name, password, surname, user_role, annual_salary) VALUES ('aa', 'Andrew', 'aa', 'Ivanov', 4, 12000);
INSERT INTO loyalty.user (login, name, password, surname, user_role, annual_salary) VALUES ('dd', 'Daniel', 'dd', 'Redcliff', 0, 12333);
INSERT INTO loyalty.user (login, name, password, surname, user_role, annual_salary) VALUES ('ss', 'Sandra', 'ss', 'Salamandra', 3, 43333);
INSERT INTO loyalty.user (login, name, password, surname, user_role, annual_salary) VALUES ('qq', 'Quine', 'qq', 'Jule', 4, 56664);
INSERT INTO loyalty.user (login, name, password, surname, user_role, annual_salary) VALUES ('xx', 'Sandra', 'xx', 'Bullock', 0, 22234);
INSERT INTO loyalty.user (login, name, password, surname, user_role, annual_salary) VALUES ('ww', 'Valery', 'ww', 'Smith', 3, 66664);
INSERT INTO loyalty.user (login, name, password, surname, user_role, annual_salary) VALUES ('jj', 'Jane', 'jj', 'Jock', 1, 55644);
INSERT INTO loyalty.user (login, name, password, surname, user_role, annual_salary) VALUES ('kk', 'Nancy', 'kk', 'Dirk', 2, 23454);
INSERT INTO loyalty.user (login, name, password, surname, user_role, annual_salary) VALUES ('oo', 'Oliver', 'oo', 'Sanders', 1, 36345);
INSERT INTO loyalty.user (login, name, password, surname, user_role, annual_salary) VALUES ('cc', 'Casedy', 'cc', 'Kim', 0, 67567);
INSERT INTO loyalty.user (login, name, password, surname, user_role, annual_salary) VALUES ('er', 'Melany', 'er', 'Je', 2, 10000);
INSERT INTO loyalty.user (login, name, password, surname, user_role, annual_salary) VALUES ('cv', 'Canve', 'cv', 'Kim', 3, 12000);
INSERT INTO loyalty.user (login, name, password, surname, user_role, annual_salary) VALUES ('gf', 'Girl', 'gf', 'Gina', 1, 12333);
INSERT INTO loyalty.user (login, name, password, surname, user_role, annual_salary) VALUES ('nk', 'Nina', 'nk', 'Ninishna', 4, 43333);
INSERT INTO loyalty.user (login, name, password, surname, user_role, annual_salary) VALUES ('dn', 'Dana', 'dn', 'Borisova', 2, 56664);
INSERT INTO loyalty.user (login, name, password, surname, user_role, annual_salary) VALUES ('ed', 'Erie', 'ed', 'Nen', 0, 22234);
INSERT INTO loyalty.user (login, name, password, surname, user_role, annual_salary) VALUES ('oi', 'Oliver', 'oi', 'Endy', 1, 66664);
INSERT INTO loyalty.user (login, name, password, surname, user_role, annual_salary) VALUES ('ni', 'Nick', 'ni', 'Nickerson', 2, 55644);
INSERT INTO loyalty.user (login, name, password, surname, user_role, annual_salary) VALUES ('ser', 'Serjio', 'ser', 'Petrovich', 0, 23454);
INSERT INTO loyalty.user (login, name, password, surname, user_role, annual_salary) VALUES ('ivan', 'Ivan', 'ivan', 'Nicolaevich', 0, 36345);
INSERT INTO loyalty.user (login, name, password, surname, user_role, annual_salary) VALUES ('petr', 'Petr', 'petr', 'Nicolaevich', 0, 67567);
INSERT INTO loyalty.user (login, name, password, surname, user_role, annual_salary) VALUES ('nic', 'Nickolay', 'ivan', 'Nicolaevich', 0, 10000);
INSERT INTO loyalty.user (login, name, password, surname, user_role, annual_salary) VALUES ('bin', 'Bogdan', 'ivan', 'Nicolaevich', 0, 12000);
INSERT INTO loyalty.user (login, name, password, surname, user_role, annual_salary) VALUES ('nina', 'Nina', 'ivan', 'Nicolaevich', 0, 12333);
INSERT INTO loyalty.user (login, name, password, surname, user_role, annual_salary) VALUES ('olga', 'Olga', 'ivan', 'Nicolaevich', 0, 43333);
INSERT INTO loyalty.user (login, name, password, surname, user_role, annual_salary) VALUES ('nast', 'Anastatia', 'ivan', 'Nicolaevich', 0, 56664);
INSERT INTO loyalty.user (login, name, password, surname, user_role, annual_salary) VALUES ('denis', 'Denis', 'ivan', 'Nicolaevich', 0, 22234);
INSERT INTO loyalty.user (login, name, password, surname, user_role, annual_salary) VALUES ('luc', 'Lucia', 'ivan', 'Nicolaevich', 0, 66664);
INSERT INTO loyalty.user (login, name, password, surname, user_role, annual_salary) VALUES ('dana', 'Dana', 'ivan', 'Nicolaevich', 0, 55644);
INSERT INTO loyalty.user (login, name, password, surname, user_role, annual_salary) VALUES ('vanya', 'Vanya', 'ivan', 'Nicolaevich', 0, 23454);
INSERT INTO loyalty.user (login, name, password, surname, user_role, annual_salary) VALUES ('gerg', 'Georgy', 'ivan', 'Nicolaevich', 0, 36345);
INSERT INTO loyalty.user (login, name, password, surname, user_role, annual_salary) VALUES ('drv', 'Demitri', 'ivan', 'Nicolaevich', 0, 67567);
INSERT INTO loyalty.user (login, name, password, surname, user_role, annual_salary) VALUES ('kiz', 'Kizil', 'ivan', 'Nicolaevich', 0, 34233);

# Inserting tasks data
INSERT INTO loyalty.task (description, last_updated_at, posted_at, title) VALUES ('Create db for production.', '2017-12-30 18:03:49', '2017-12-30 13:03:54', 'Create DB');
INSERT INTO loyalty.task (description, last_updated_at, posted_at, title) VALUES ('Create schema for production.', '2017-12-17 13:03:49', '2017-12-30 13:03:54', 'Create Schema');
INSERT INTO loyalty.task (description, last_updated_at, posted_at, title) VALUES ('Adjust db for production.', '2017-12-13 13:03:49', '2017-12-30 13:03:54', 'Adjust DB');
INSERT INTO loyalty.task (description, last_updated_at, posted_at, title) VALUES ('Manage db for production.', '2017-12-15 13:03:49', '2017-12-30 13:03:54', 'Manage DB');
INSERT INTO loyalty.task (description, last_updated_at, posted_at, title) VALUES ('Manipulate data for db for production.', '2017-12-23 13:03:49', '2017-12-30 13:03:54', 'Manipulate data for DB');
INSERT INTO loyalty.task (description, last_updated_at, posted_at, title) VALUES ('Create data in db for production.', '2017-12-26 13:03:49', '2017-12-30 13:03:54', 'Create data in DB');
INSERT INTO loyalty.task (description, last_updated_at, posted_at, title) VALUES ('Retrieve statistics from db for production.', '2017-11-30 13:03:49', '2017-12-30 13:03:54', 'Retrieve statistics');
INSERT INTO loyalty.task (description, last_updated_at, posted_at, title) VALUES ('Create db for production.', '2017-12-30 13:03:49', '2017-12-30 13:03:54', 'Create DB');
INSERT INTO loyalty.task (description, last_updated_at, posted_at, title) VALUES ('Create beans for production.', '2017-12-26 13:03:49', '2017-12-30 13:03:54', 'Create beans');
INSERT INTO loyalty.task (description, last_updated_at, posted_at, title) VALUES ('Create accountant view for production.', '2017-12-31 13:03:49', '2017-12-30 13:03:54', 'Create Accountant view');
INSERT INTO loyalty.task (description, last_updated_at, posted_at, title) VALUES ('Create manager view for production.', '2017-12-23 13:03:49', '2017-12-30 13:03:54', 'Create manager view');
INSERT INTO loyalty.task (description, last_updated_at, posted_at, title) VALUES ('Create employee view for production.', '2017-12-22 13:03:49', '2017-12-30 13:03:54', 'Create employee view');
INSERT INTO loyalty.task (description, last_updated_at, posted_at, title) VALUES ('Create admin view for production.', '2017-12-21 13:03:49', '2017-12-30 13:03:54', 'Create admin view');
